title: Siddhartha Bhunia
logo: /assets/img/logo.png
description: I am working on IOT and Embedded System from last 5 years, currently i am learning Machine learning to deploy on my field of Automation
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
